def COLOR_MAP = [
  "SUCCESS": "#2EB67D",
  "FAILURE": "#E01E5A",
  "UNSTABLE": "#ECB22E",
  "ABORTED": "#A30200"
]


pipeline {
    agent any
    tools {
        maven "MAVEN3.9.9"
        jdk "JDK17"
    }
    
    environment {
        cluster = 'vproappProd'
        service = 'vprofileapptask-service-Prod'
    }

    stages {
        stage('Deploy to staging ECS') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-west-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                } 
            }
        }
    }
    
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#jenkins-cicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }

}